- src/providers/native/index.ts
With this we can have spawned processes be able to use system utils (like yarn) by default.
> Inherit process.env.PATH to spawned process

- src/index.ts
- src/providers/native/index.ts
- src/runtimes.ts
- test/test.ts
This will be used by `now dev` to launch the builders in a forked child process using the same version of `node` that is used by builders in production, but not actually be a `fun` lambda function.
Also adds the `${cacheDir}/bin` of the runtime to the `PATH` env var in the fun function so that it has access to the binaries provided there by default.
> Export the `initializeRuntime()` function and allow string runtime names

- src/runtimes/go1.x/bootstrap.go
This PR will fix `undefined: syscall.Kill`.
But It seem that there are no alternative for `syscall.SysProcAttr{Setpgid: true}` on Windows.
Related: https://github.com/zeit/now-builders/pull/481
> Terminate child process work on Windows

- src/runtime-server.ts
Instead of the default `1mb` limit. This matches AWS Lambda's "Invocation Payload" response limit documented at https://docs.aws.amazon.com/lambda/latest/dg/limits.html
Related to: https://spectrum.chat/zeit/now/error-body-exceeded-1mb-limit~69845eac-55c7-412e-b4e5-deba469cfe26
> Add `6mb` response limit

- src/providers/native/index.ts
- src/types.ts
- test/test.ts
- tsconfig.json
LambdaParams.Environment.Variables checks for "allowed variables" and prevents
users from setting AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. This makes
sense as Lambda also prevents setting these through the API.
Setting them is useful however to replicate the actual deployment environment,
meaning you don't have to pass these manually to the AWS SDK when running
locally with a conditional check.
Never sure how to do these dependent PRs.... I'll delete the other one.
>  Allow passing AccessKeyId and SecretAccessKey in params

- package.json
- yarn.lock
This PR bump `micro` that contain a fix for handle `DeprecationWarning`
```
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
> Bump `micro` version

- package.json
- src/index.ts
- src/providers/native/index.ts
- src/runtime-server.ts
- src/runtimes.ts
- src/runtimes/go1.x/index.ts
- src/runtimes/nodejs/bootstrap.ts
- src/unzip.ts
- test/test.ts
- tsconfig.json
- yarn.lock
Also updates config dir logic to use `xdg-app-paths` module instead of `cache-or-tmp-directory` module, for consistency with the `now` repo.
> Enable `esModuleInterop` option for TypeScript config

- src/runtimes/nodejs/bootstrap
- src/runtimes/nodejs10.x/bootstrap
- src/runtimes/nodejs6.10/bootstrap
- src/runtimes/nodejs8.10/bootstrap
- src/runtimes/python/bootstrap
- src/runtimes/python2.7/bootstrap
- src/runtimes/python3.6/bootstrap
- src/runtimes/python3.7/bootstrap
So that POSIX `/bin/sh` may be used instead of Bash, for platforms that do not have Bash installed by default (i.e. Alpine Linux).
> Remove `-o pipefail` option from bootstrap for POSIX compliance

- README.md
- src/runtimes.ts
- src/runtimes/python/bootstrap
- src/runtimes/python/bootstrap.ts
- src/runtimes/python3/bootstrap
- src/runtimes/python3/bootstrap.ts
- src/runtimes/python3/index.ts
- test/test.ts
This PR adds a new runtime for `python3` that uses the system's python installation and then fallback to `python`.
Related to
- https://github.com/zeit/now/issues/2495
- https://github.com/zeit/now/issues/2849
- https://github.com/zeit/now/issues/2860
> Add support for system installed `python3` runtime

- test/functions/nodejs-exit/handler.js
- test/functions/nodejs-reference-error/handler.js
- test/test.ts
Ensures that the `invoke()` function returns quickly with the expected error message when a Node.js `ReferenceError` occurs in the lambda code.
> Add `nodejs-reference-error` test case

- src/runtime-server.ts
- test/functions/nodejs-exit/handler.js
- test/test.ts
Before, the `invoke()` function would never resolve. Now it properly throws an error.
> Fix `invoke()` resolving upon lambda initialization error

- src/runtime-server.ts
- src/runtimes/nodejs6.10/bootstrap.ts
- src/runtimes/nodejs8.10/bootstrap.ts
- src/runtimes/python2.7/bootstrap.ts
- src/runtimes/python3.6/bootstrap.ts
- src/runtimes/python3.7/bootstrap.ts
- test/test.ts
This is so that the runtime initialization error case has a proper `RequestID`, and not `null`.
> Calculate the `RequestId` earlier

- src/providers/native/index.ts
Doing this alters the generated TypeScript declaration file to not import the `generic-pool` type declarations, which are a dev dependency.
This is useful for downstream consumers that compile with `tsc` (and avoids us having to move the `@types/generic-pool` module from `devDependencies` into `dependencies`).
> Use `private` fields for `NativeProvider` class

- package.json
- src/providers/native/index.ts
- yarn.lock
In the past, it has been witnessed that `bootstrap` child processes remain alive even after `fn.destroy()` is invoked. The circumstances for when/why this happens is uncertain at this time, however we are using `tree-kill` in Now CLI as well to handle killing sub-tree child processes that builders create.
> Use the `tree-kill` module to shut down lambda functions

- package.json
So that the `test` directory does not get published to npm.
> Update `files` array in package.json file

- src/runtimes/go1.x/bootstrap.go
Possibly a fix for https://github.com/zeit/now/issues/3323.
Unfortunately, I can't think of a good way to test for this behavior.
> [go1.x] Set `client.Timeout` to 0 for infinite

- src/runtimes/go1.x/bootstrap.go
This line is causing the following error on Windows:
```
unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr
```
> Fix bootstrap.go on Windows

- package.json
- src/runtimes/go1.x/bootstrap.go
- src/runtimes/go1.x/bootstrap.ts
- src/runtimes/go1.x/filename.ts
- src/runtimes/go1.x/index.ts
- yarn.lock
This PR adds a file extension `.exe` for windows when using the Go runtime.
It also filters out `Setpgid` which is not available on Windows.
> Fix filename for Go bootstrap on Windows

- package.json
- src/install-node.ts
- src/install-python.ts
- test/test.ts
- yarn.lock
For Node.js, official binaries are not provided for versions <= 14.
For Python, the binaries compiled manually are also only for x64, so force it in that case as well.
> Force x64 for binaries on Apple M1

- src/runtimes/go1.x/bootstrap.go
https://github.blog/changelog/2022-04-25-git-io-deprecation/
> Resolve git.io

- src/runtimes/python3/bootstrap.ts
> fix: python3 bootstrap handler should be called only once

- src/errors.ts
- src/index.ts
While there's nothing wrong with using `new.target`, it turns out that `ncc` has been stripping them for some reason. Subsequently, if an error occurred while invoking a lambda function, the actual error would never be displayed since the `LambdaError` creation would fail with an error `Object.setPrototypeOf()` with an object or `null`.
For example, the original code looked like this:
```
Object.setPrototypeOf(this, new.target.prototype);
```
But `ncc` would output:
```
Object.setPrototypeOf(this, /* unsupported import.meta.prototype */ undefined);
```
I couldn't find any instances where we derive errors from `LambdaError` or `ValidationError`, so it shouldn't be a problem to replace `new.target` with the class name.
This should partially fix https://github.com/vercel/vercel/issues/8000.
> fix: Ref custom error classes instead of new.target

- .github/workflows/test.yml
This was using `matrix.node` in some places but `matrix.node_version` in others
> fix(ci): handle node version

- README.md
- src/runtimes/python3/index.ts
- test/test.ts
Back in #34 we added Python 3 that would fallback to system Python 3 if it exists. In MacOS 12.3 Apple [removed system python](https://discussions.apple.com/thread/254787935#:~:text=Apple%20removed%20the%20Python%202.7,and%20unsupported%20by%20Python.org).
This PR updates `python3` to behave like the other python runtimes by calling `installPython`.
See:
* https://github.com/orgs/vercel/discussions/2524
* https://vercel.sentry.io/issues/1148731861/?query=is%3Aunresolved+python3
> No longer rely on system Python for installs of python3 runtime

- package.json
- pnpm-lock.yaml
I was using [`trunk check`](https://trunk.io/products/check) on my own repo and noticed some moderately severe vulnerabilities with the dependencies of `@vercel/fun`:
```text
ISSUES
pnpm-lock.yaml:175:0
175:0  medium  Vulnerability in 'debug': nodejs-debug: Regular expression Denial of Service. Current version is vulnerable: 4.1.1. Patch available: upgrade to 2.6.9, 3.1.0, 3.2.7, 4.3.1   trivy/CVE-2017-16137
3517:0  medium  Vulnerability in 'semver': Regular expression denial of service. Current version is vulnerable: 7.3.5. Patch available: upgrade to 7.5.2, 6.3.1, 5.7.2 or higher.            trivy/CVE-2022-25883
```
You can find these with `pnpm audit --prod` too
```text
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ moderate            │ semver …
```
> update prod packages with CVE vulnerabilities

- package.json
- pnpm-lock.yaml
- src/providers/native/index.ts
- src/runtime-server.ts
In my NextJS projects I get the following warning from npm:
`npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`
I tracked it down to this package, and I found the instances where uuid() was used and replaced it with crypto.randomUUID(), then I removed the package and its types. Crypto's function is actually supposed to be much faster than using the uuid package.
> Remove uuid package and replace with crypto.randomUUID()
